# astral-supernova — astral journey
# https://github.com/kmf/astral-journey

background #fdf9ec
foreground #292140
selection_background #664466
selection_foreground #1c1730
cursor #b65608
cursor_text_color #fdf9ec
url_color #2f5fc7

active_border_color #e2d8ba
inactive_border_color #efe8cf
bell_border_color #d62e3f

active_tab_background #fdf9ec
active_tab_foreground #292140
inactive_tab_background #f6f0dc
inactive_tab_foreground #5d5c78

# normal
color0 #292140
color1 #d62e3f
color2 #1d8156
color3 #946900
color4 #2f5fc7
color5 #a34fa8
color6 #006699
color7 #f6f0dc

# bright
color8 #5d5c78
color9 #c22f3e
color10 #187a4f
color11 #9c6e00
color12 #2551ad
color13 #8f4494
color14 #005982
color15 #1c1730
