# astral-blackhole — astral journey
# https://github.com/kmf/astral-journey

background #0d0f1e
foreground #ebe8d2
selection_background #664466
selection_foreground #fdfbe4
cursor #ff9933
cursor_text_color #0d0f1e
url_color #6a97ea

active_border_color #2a2f4d
inactive_border_color #1c2038
bell_border_color #ff6e6e

active_tab_background #0d0f1e
active_tab_foreground #ebe8d2
inactive_tab_background #14172a
inactive_tab_foreground #767ba6

# normal
color0 #1c2038
color1 #ff6e6e
color2 #7ed4a3
color3 #ffcc66
color4 #6a97ea
color5 #cc99cc
color6 #38a8d0
color7 #ebe8d2

# bright
color8 #3f4670
color9 #ff8a80
color10 #98e0ba
color11 #ffff99
color12 #99ccff
color13 #d9a9e0
color14 #5cc0e0
color15 #fdfbe4
