# astral-supernova — astral journey
# https://github.com/kmf/astral-journey

[cursor]
color=fdf9ec b65608

[colors]
foreground=292140
background=fdf9ec
selection-foreground=1c1730
selection-background=664466

regular0=292140
regular1=d62e3f
regular2=1d8156
regular3=946900
regular4=2f5fc7
regular5=a34fa8
regular6=006699
regular7=f6f0dc

bright0=5d5c78
bright1=c22f3e
bright2=187a4f
bright3=9c6e00
bright4=2551ad
bright5=8f4494
bright6=005982
bright7=1c1730
