# astral-blackhole — astral journey
# https://github.com/kmf/astral-journey

[cursor]
color=0d0f1e ff9933

[colors]
foreground=ebe8d2
background=0d0f1e
selection-foreground=fdfbe4
selection-background=664466

regular0=1c2038
regular1=ff6e6e
regular2=7ed4a3
regular3=ffcc66
regular4=6a97ea
regular5=cc99cc
regular6=38a8d0
regular7=ebe8d2

bright0=3f4670
bright1=ff8a80
bright2=98e0ba
bright3=ffff99
bright4=99ccff
bright5=d9a9e0
bright6=5cc0e0
bright7=fdfbe4
