# astral-supernova — astral journey
# https://github.com/kmf/astral-journey

[colors.primary]
background = "#fdf9ec"
foreground = "#292140"

[colors.cursor]
cursor = "#b65608"
text = "#fdf9ec"

[colors.vi_mode_cursor]
cursor = "#1d8156"
text = "#fdf9ec"

[colors.selection]
background = "#664466"
text = "#1c1730"

[colors.search.matches]
background = "#946900"
foreground = "#fdf9ec"

[colors.search.focused_match]
background = "#b65608"
foreground = "#fdf9ec"

[colors.hints.start]
background = "#946900"
foreground = "#fdf9ec"

[colors.hints.end]
background = "#5d5c78"
foreground = "#fdf9ec"

[colors.footer_bar]
background = "#f6f0dc"
foreground = "#292140"

[colors.normal]
black = "#292140"
red = "#d62e3f"
green = "#1d8156"
yellow = "#946900"
blue = "#2f5fc7"
magenta = "#a34fa8"
cyan = "#006699"
white = "#f6f0dc"

[colors.bright]
black = "#5d5c78"
red = "#c22f3e"
green = "#187a4f"
yellow = "#9c6e00"
blue = "#2551ad"
magenta = "#8f4494"
cyan = "#005982"
white = "#1c1730"
